# Generated by Django 2.2.4 on 2019-11-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tr1', models.CharField(max_length=20)),
                ('tr2', models.CharField(max_length=30)),
                ('tr3', models.CharField(max_length=30)),
                ('tr4', models.CharField(max_length=30)),
                ('tr5', models.CharField(max_length=30)),
                ('tr6', models.CharField(max_length=30)),
            ],
        ),
    ]
