# Generated by Django 2.2.4 on 2019-11-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atvtc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='table',
        ),
    ]
