# Generated by Django 2.2.4 on 2019-11-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atvtc_app', '0002_auto_20191124_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='tr1',
            new_name='ter1',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='tr2',
            new_name='ter2',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='tr3',
            new_name='ter3',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='tr4',
            new_name='ter4',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='tr5',
            new_name='ter5',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='tr6',
            new_name='ter6',
        ),
    ]
